# Site settings
title: Sherminta Lawrence
email: shermintalawrence@gmail.com
description: Interface & Data Analyst | Healthcare Interoperability
baseurl: ""
url: "https://mitajuanita.github.io"


# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Author information
author:
  name: Sherminta Lawrence
  email: shermintalawrence@gmail.com
  github_username: MitaJuanita
  linkedin_username: shermintalawrence

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"